USE [DEMOS]
GO

/****** Object:  Table [dbo].[lmsAdminProfession]    Script Date: 7/06/2021 15:58:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[lmsAdminProfession](
	[ID_PROFESSION] [int] IDENTITY(1,1) NOT NULL,
	[NAME_PROFESSION] [varchar](50) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_lmsAdminProfession] PRIMARY KEY CLUSTERED 
(
	[ID_PROFESSION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[lmsAdminProfession] ADD  CONSTRAINT [DF_lmsAdminProfession_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO


